pipeline:
  identifier: Build_deepak221306_DevopsBasics_1709011593852
  name: Build DevopsBasics
  orgIdentifier: default
  projectIdentifier: javaproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: deepak221306/DevopsBasics
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: WAR-FILE
                  identifier: WARFILE
                  spec:
                    shell: Sh
                    command: mvn clean install
              - step:
                  type: S3Upload
                  name: S3Upload_war
                  identifier: S3Upload_war
                  spec:
                    connectorRef: AWSConnector
                    region: us-east-1
                    bucket: webappupload
                    sourcePath: /harness/target/webapp-1.war
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: Deployment
        identifier: Deployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: javaservice
            serviceInputs:
              serviceDefinition:
                type: Ssh
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: javainfra
          execution:
            steps:
              - step:
                  type: Command
                  name: Command_1
                  identifier: Command_1
                  spec:
                    onDelegate: false
                    environmentVariables: []
                    outputVariables: []
                    commandUnits:
                      - identifier: javacmd
                        name: javacmd
                        type: DownloadArtifact
                        spec:
                          destinationPath: /opt/apache-tomcat-9.0.86/webapps
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        delegateSelectors:
          - docker-delegate
  allowStageExecutions: true
